name: aeproject

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
      - run: npm install -g @aeternity/aeproject@4.0.0-beta.3
      - run: aeproject env && sleep 3
      - run: aeproject test
